theme:minima
title: KP Enterprises
author: Emmanuel Sodipe
email: kaypraiseenterprises@gmail.com
description: > # Welcome to KP Enterprises. Your SATISFACTION is our pleasure

# social links
twitter_username: kaypraise_05
github_username:  kaypraise

show_excerpts: true # set to false to remove excerpts on the homepage
